CREATE TABLE person (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
full_name varchar(100) NOT NULL UNIQUE,
year_of_birth int NOT NULL
);

CREATE TABLE book (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(100) NOT NULL,
author varchar(100) NOT NULL,
year int NOT NULL,
person_id int REFERENCES Person(id) ON DELETE SET NULL
);

INSERT INTO person VALUES(2, 'Петров Петр Петрович', 1960);
INSERT INTO person VALUES(3, 'Алексеев Алексей Алексеевич', 1989);
INSERT INTO person VALUES(4, 'Познер Владимир Владимирович', 1944);
INSERT INTO person VALUES(1, 'Иванов Иван Иванович', 1970);

INSERT INTO book(id, title, author, year) VALUES(2, 'Над пропастью во ржи', 'Джером Сэлинджер', 1951);
INSERT INTO book(id, title, author, year) VALUES(3, 'Бытие и время', 'Мартин Хайдеггер', 1927);
INSERT INTO book(id, title, author, year) VALUES(4, 'Философия Java', 'Брюс Эккель', 2018);
INSERT INTO book(id, title, author, year) VALUES(5, 'День опричника', 'Владимир Сорокин', 2006);
INSERT INTO book(id, title, author, year) VALUES(6, 'Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
INSERT INTO book(id, title, author, year) VALUES(7, 'Игра в бисер', 'Герман Гессе', 1943);
INSERT INTO book(id, title, author, year) VALUES(1, 'Психопатология обыденной жизни', 'Зигмунд Фрейд', 1905);

